#!/usr/bin/env ruby
#
require 'sinatra'
require 'erb'
require 'json'

require_relative 'survey_questions'
get '/' do
    @questions = SurveyQuestions::SAMPLE_QUESTIONS
    erb :index
end

post '/' do
    erb :results
end
